# *Data Cleaning*

* Importing the data set(CSV)
* Observe the data set
    * Identify the rows/columns and their relation 
    * Identify the index column (Primary key column)
    * Check if there are any duplicate columns
    * Which rows to be skipped
* Assign the index column (To avoid creation of new index column )
* Skip irrelevant rows (To avoid display of index row)
* Drop dupliacte / irrelevant columns (For faster Operations)


# *Data Retrieval*

* Retrive Index columns -- df.index
* Columns names    -- df.columns
* second columns   -- df[Column_name]  # output in series format  
* any columns     -- df[[Column_name]] # output in DataFrame
* First Row      -- df.head(1)
* Access single row -- df.iloc[index]
* Access single cell

In [50]:
import pandas as pd

df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)

for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

names_ids = df.index.str.split('\s\(') # split the index by '('

df.index = names_ids.str[0] # the [0] element is the country name (new index) 
df['ID'] = names_ids.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)

df = df.drop('Totals')
df.head()

# Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  \
Afghanistan        13     0       0       2      2         0       0   
Algeria            12     5       2       8     15         3       0   
Argentina          23    18      24      28     70        18       0   
Armenia             5     1       2       9     12         6       0   
Australasia         2     3       4       5     12         0       0   

             Silver.1  Bronze.1  Total.1  # Games  Gold.2  Silver.2  Bronze.2  \
Afghanistan         0         0        0       13       0         0         2   
Algeria             0         0        0       15       5         2         8   
Argentina           0         0        0       41      18        24        28   
Armenia             0         0        0       11       1         2         9   
Australasia         0         0        0        2       3         4         5   

             Combined total   ID  
Afghanistan               2  AFG  
Algeria                  15  ALG  
Argentina                70  ARG  
Armenia                  12  ARM  
Australasia              12  ANZ

In [169]:
df["Gold"] # getting
df["Gold"][4]  # getting row, column  # returns the gold medals won by the fifth country(row,column)
df[:1]    # returns 0th row with columns name
df.index[1] # returns the second country name
df.loc["Afghanistan"]
df.iloc[4][1]  # return 3rd row 1st column ()
df["Gold"][4]  # return gold medal column,3rd row
df.loc["India","Combined total"]  # df.loc["India","Combined total"] -- return total medals won by india
df.columns
df["Combined total"]
#df.loc["India"][-1]
df.loc["United States"]
df.index[0]
df.index[-1]
df["# Games"]
df["# Summer"][9] # return total no. of games participated by 10th country
df["Combined total"][-1] # returns total medals of last country
df.loc["United States","Gold.2"] # return total number of gold medals in united states
abs(df.loc["United States","Gold"]-df.loc["China","Gold"])
df["Gold.1"].max()
#df["Gold.1"].argmax()  
df["Gold"].sum()
sum(df["Gold"])
df[df["Gold"] == df["Gold"].max()].index[0]
df[df["Total"] == df["Total"].max()]
df[df["Combined total"] == df["Combined total"].max()].index[0]
df1=df[(df["Gold"]>0) & (df["Gold.1"]>0)]
df1
(abs(df1["Gold"]-df1["Gold.1"])/df1["Gold.2"]).idxmax()


'Bulgaria'

In [49]:
import pandas as pd 
df = pd.read_csv("olympics.csv",index_col=0,skiprows=1)
df.index
df.columns
df.index[0]
df["Total"]# axis is used in function 
df[["Total.1"]] # the output  in DF
df.head(1)
df.iloc[0]
df.index
#df.loc['Yugoslavia (YUG) [YUG]']
df.index[0]
df.columns

Index(['№ Summer', '01 !', '02 !', '03 !', 'Total', '№ Winter', '01 !.1',
       '02 !.1', '03 !.1', 'Total.1', '№ Games', '01 !.2', '02 !.2', '03 !.2',
       'Combined total'],
      dtype='object')

In [209]:
# Calculate second most popular state using censun

dff=pd.read_csv("census.csv")
dff=dff.set_index("STNAME")
dff=dff.sort_values(by= "CENSUS2010POP")
dff
dff[["CENSUS2010POP"]].index[0]

dff["STNAME"].value_counts()

KeyError: 'STNAME'

In [ ]:
dff[""]

# Pandas Topics
 * Convert Dict to DataFrames -- pd.DtaFrame({...})
 * skiprows  -- skiprows = value
 * Get top rows from df -- df.head(10)
 * Get bottom rows from df -- df.tail(10)
 * Get specified rows from df -- df.iloc[index]  or -- df.iloc[[index_val1,index_val2]]
 * Get specified row and columns -- df.loc[[Row_names],[Column_names]]
 * Get Max of column -- df[column_name].max()
 * Get attributes of Column -- df[column_name].min() df[column_name].mean()  df[column_name].median() 
 * set row as index by using --  usecol= value
 * Get Columns -- df.columns
 * Get columns slicing -- df.columns[:]
 * rename Column names  -- pd.rename(columns= { "old column name" = "new Column name"})
 * Get specified Columns in DataFrame -- df[[ column_name1,Column_name2]]
 * Get column in Series -- pd.Series(df[column_name])
 * To remove columns -- pd.drop(colum_name,axis=1,inplace=True)
 * To Convert Columns as Index -- pd.set_index(column_name)
 * To reset Index into Columns -- pd.reset_index()
 * To get index of specified value in a column -- df[column_name].idxmax() or -- df[Column_name].argmax()
 * Replace anything -- df.replace(old_val,new_val)
 * Merge of 2 files  -- pd.merge(file1,file2,how=inner/outer,right_on=Column_name,left_on=Column_name)

In [14]:
import numpy as np

a = np.arange(10) # to create numpy array with 10 elements 

print(np.roll(a,4) ) # to create numpy array and shifts circularly np.roll(itarable,no. of positions)
np.roll(a,-4)

[6 7 8 9 0 1 2 3 4 5]


array([4, 5, 6, 7, 8, 9, 0, 1, 2, 3])

In [20]:
import pandas as pd
dir(pd)

['Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NaT',
 'Panel',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseArray',
 'SparseDataFrame',
 'SparseDtype',
 'SparseSeries',
 'TimeGrouper',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_hashtable',
 '_lib',
 '_libs',
 '_np_version_under1p13',
 '_np_version_under1p14',
 '_np_version_under1p15',
 '_np_version_under1p16',
 '_np_version_under1p17

In [137]:
import pandas as pd

df= pd.read_csv("world_bank2.csv")
df

Data Source  \
0                                                  NaN   
1                                    Last Updated Date   
2                                                  NaN   
3                                         Country Name   
4                                                Aruba   
5                                              Andorra   
6                                          Afghanistan   
7                                               Angola   
8                                              Albania   
9                                           Arab World   
10                                United Arab Emirates   
11                                           Argentina   
12                                             Armenia   
13                                      American Samoa   
14                                 Antigua and Barbuda   
15                                           Australia   
16                                             Austria   
17                                          Azerbaijan   
18                                             Burundi   
19                                             Belgium   
20                                               Benin   
21                                        Burkina Faso   
22                                          Bangladesh   
23                                            Bulgaria   
24                                             Bahrain   
25                                        Bahamas, The   
26                              Bosnia and Herzegovina   
27                                             Belarus   
28                                              Belize   
29                                             Bermuda   
..                                                 ...   
238  Middle East & North Africa (IDA & IBRD countries)   
239                                        Timor-Leste   
240                                              Tonga   
241                            South Asia (IDA & IBRD)   
242          Sub-Saharan Africa (IDA & IBRD countries)   
243                                Trinidad and Tobago   
244                                            Tunisia   
245                                             Turkey   
246                                             Tuvalu   
247                                           Tanzania   
248                                             Uganda   
249                                            Ukraine   
250                                Upper middle income   
251                                            Uruguay   
252                                      United States   
253                                         Uzbekistan   
254                     St. Vincent and the Grenadines   
255                                      Venezuela, RB   
256                             British Virgin Islands   
257                              Virgin Islands (U.S.)   
258                                            Vietnam   
259                                            Vanuatu   
260                                 West Bank and Gaza   
261                                              World   
262                                              Samoa   
263                                        Yemen, Rep.   
264                                       South Africa   
265                                   Congo, Dem. Rep.   
266                                             Zambia   
267                                           Zimbabwe   

    World Development Indicators                                Unnamed: 2  \
0                            NaN                                       NaN   
1                     2016-07-22                                       NaN   
2                            NaN                                       NaN   
3                   Country Code                            Indicator Name   
4                            ABW  GDP at market prices (

In [138]:
df=df.replace("NaN","")
df

Data Source  \
0                                                  NaN   
1                                    Last Updated Date   
2                                                  NaN   
3                                         Country Name   
4                                                Aruba   
5                                              Andorra   
6                                          Afghanistan   
7                                               Angola   
8                                              Albania   
9                                           Arab World   
10                                United Arab Emirates   
11                                           Argentina   
12                                             Armenia   
13                                      American Samoa   
14                                 Antigua and Barbuda   
15                                           Australia   
16                                             Austria   
17                                          Azerbaijan   
18                                             Burundi   
19                                             Belgium   
20                                               Benin   
21                                        Burkina Faso   
22                                          Bangladesh   
23                                            Bulgaria   
24                                             Bahrain   
25                                        Bahamas, The   
26                              Bosnia and Herzegovina   
27                                             Belarus   
28                                              Belize   
29                                             Bermuda   
..                                                 ...   
238  Middle East & North Africa (IDA & IBRD countries)   
239                                        Timor-Leste   
240                                              Tonga   
241                            South Asia (IDA & IBRD)   
242          Sub-Saharan Africa (IDA & IBRD countries)   
243                                Trinidad and Tobago   
244                                            Tunisia   
245                                             Turkey   
246                                             Tuvalu   
247                                           Tanzania   
248                                             Uganda   
249                                            Ukraine   
250                                Upper middle income   
251                                            Uruguay   
252                                      United States   
253                                         Uzbekistan   
254                     St. Vincent and the Grenadines   
255                                      Venezuela, RB   
256                             British Virgin Islands   
257                              Virgin Islands (U.S.)   
258                                            Vietnam   
259                                            Vanuatu   
260                                 West Bank and Gaza   
261                                              World   
262                                              Samoa   
263                                        Yemen, Rep.   
264                                       South Africa   
265                                   Congo, Dem. Rep.   
266                                             Zambia   
267                                           Zimbabwe   

    World Development Indicators                                Unnamed: 2  \
0                            NaN                                       NaN   
1                     2016-07-22                                       NaN   
2                            NaN                                       NaN   
3                   Country Code                            Indicator Name   
4                            ABW  GDP at market prices (

In [179]:
df2=pd.read_csv("olympics.csv",index_col=0,skiprows=1)
df2.head(5)

№ Summer  01 !  02 !  03 !  Total  № Winter  01 !.1  \
Afghanistan (AFG)              13     0     0     2      2         0       0   
Algeria (ALG)                  12     5     2     8     15         3       0   
Argentina (ARG)                23    18    24    28     70        18       0   
Armenia (ARM)                   5     1     2     9     12         6       0   
Australasia (ANZ) [ANZ]         2     3     4     5     12         0       0   

                         02 !.1  03 !.1  Total.1  № Games  01 !.2  02 !.2  \
Afghanistan (AFG)             0       0        0       13       0       0   
Algeria (ALG)                 0       0        0       15       5       2   
Argentina (ARG)               0       0        0       41      18      24   
Armenia (ARM)                 0       0        0       11       1       2   
Australasia (ANZ) [ANZ]       0       0        0        2       3       4   

                         03 !.2  Combined total  
Afghanistan (AFG)             2               2  
Algeria (ALG)                 8              15  
Argentina (ARG)              28              70  
Armenia (ARM)                 9              12  
Australasia (ANZ) [ANZ]       5              12

In [37]:
df2[["01 !","02 !"]].head()

01 !  02 !
Afghanistan (AFG)           0     0
Algeria (ALG)               5     2
Argentina (ARG)            18    24
Armenia (ARM)               1     2
Australasia (ANZ) [ANZ]     3     4

In [85]:
df2[["01 !","02 !"]]

01 !  02 !
Country                                                 
Afghanistan (AFG)                                0     0
Algeria (ALG)                                    5     2
Argentina (ARG)                                 18    24
Armenia (ARM)                                    1     2
Australasia (ANZ) [ANZ]                          3     4
Australia (AUS) [AUS] [Z]                      139   152
Austria (AUT)                                   18    33
Azerbaijan (AZE)                                 6     5
Bahamas (BAH)                                    5     2
Bahrain (BRN)                                    0     0
Barbados (BAR) [BAR]                             0     0
Belarus (BLR)                                   12    24
Belgium (BEL)                                   37    52
Bermuda (BER)                                    0     0
Bohemia (BOH) [BOH] [Z]                          0     1
Botswana (BOT)                                   0     1
Brazil (BRA)                                    23    30
British West Indies (BWI) [BWI]                  0     0
Bulgaria (BUL) [H]                              51    85
Burundi (BDI)                                    1     0
Cameroon (CMR)                                   3     1
Canada (CAN)                                    59    99
Chile (CHI) [I]                                  2     7
China (CHN) [CHN]                              201   146
Colombia (COL)                                   2     6
Costa Rica (CRC)                                 1     1
Ivory Coast (CIV) [CIV]                          0     1
Croatia (CRO)                                    6     7
Cuba (CUB) [Z]                                  72    67
Cyprus (CYP)                                     0     1
...                                            ...   ...
Sri Lanka (SRI) [SRI]                            0     2
Sudan (SUD)                                      0     1
Suriname (SUR) [E]                               1     0
Sweden (SWE) [Z]                               143   164
Switzerland (SUI)                               47    73
Syria (SYR)                                      1     1
Chinese Taipei (TPE) [TPE] [TPE2]                2     7
Tajikistan (TJK)                                 0     1
Tanzania (TAN) [TAN]                             0     2
Thailand (THA)                                   7     6
Togo (TOG)                                       0     0
Tonga (TGA)                                      0     1
Trinidad and Tobago (TRI) [TRI]                  2     5
Tunisia (TUN)                                    3     3
Turkey (TUR)                                    39    25
Uganda (UGA)                                     2     3
Ukraine (UKR)                                   33    27
United Arab Emirates (UAE)                       1     0
United States (USA) [P] [Q] [R] [Z]            976   757
Uruguay (URU)                                    2     2
Uzbekistan (UZB)                                 5     5
Venezuela (VEN)                                  2     2
Vietnam (VIE)                                    0     2
Virgin Islands (ISV)                             0     1
Yugoslavia (YUG) [YUG]                          26    29
Independent Olympic Participants (IOP) [IOP]     0     1
Zambia (ZAM) [ZAM]                               0     1
Zimbabwe (ZIM) [ZIM]                             3     4
Mixed team (ZZX) [ZZX]                           8     5
Totals                                        4809  4775

[147 rows x 2 columns]

In [48]:
df2[df2["01 !"]>250]


№ Summer  01 !  02 !  03 !  Total  \
Soviet Union (URS) [URS]                    9   395   319   296   1010   
United States (USA) [P] [Q] [R] [Z]        26   976   757   666   2399   
Totals                                     27  4809  4775  5130  14714   

                                     № Winter  01 !.1  02 !.1  03 !.1  \
Soviet Union (URS) [URS]                    9      78      57      59   
United States (USA) [P] [Q] [R] [Z]        22      96     102      84   
Totals                                     22     959     958     948   

                                     Total.1  № Games  01 !.2  02 !.2  03 !.2  \
Soviet Union (URS) [URS]                 194       18     473     376     355   
United States (USA) [P] [Q] [R] [Z]      282       48    1072     859     750   
Totals                                  2865       49    5768    5733    6078   

                                     Combined total  
Soviet Union (URS) [URS]                       1204  
United States (USA) [P] [Q] [R] [Z]            2681  
Totals                                        17579

In [95]:
#df2=df2.reset_index()

#df2=df2.rename(columns={"index" : "Country" })
#df2=df2.set_index("Country")
#df2.drop("level_0",axis=1,inplace=True)
df2.iloc[[9,8]]

level_0  index        Country  № Summer  01 !  02 !  03 !  Total  № Winter  \
9        9      9  Bahrain (BRN)         8     0     0     1      1         0   
8        8      8  Bahamas (BAH)        15     5     2     5     12         0   

   01 !.1  02 !.1  03 !.1  Total.1  № Games  01 !.2  02 !.2  03 !.2  \
9       0       0       0        0        8       0       0       1   
8       0       0       0        0       15       5       2       5   

   Combined total  
9               1  
8              12

In [106]:
df2.loc[9,["Country","№ Games"]]

Country    Bahrain (BRN)
№ Games                8
Name: 9, dtype: object

In [112]:
df2["01 !"].max()

4809

In [113]:
df2["01 !"].min()

0

In [114]:
df2["01 !"].mean()

65.42857142857143

In [115]:
df2["01 !"].median()

3.0

In [117]:
df2["01 !"].idxmax()

146

In [118]:
df2.loc[146,"01 !"]

4809

In [140]:
df2.iloc[146]

№ Summer             27
01 !               4809
02 !               4775
03 !               5130
Total             14714
№ Winter             22
01 !.1              959
02 !.1              958
03 !.1              948
Total.1            2865
№ Games              49
01 !.2             5768
02 !.2             5733
03 !.2             6078
Combined total    17579
Name: Totals, dtype: int64

In [180]:
import numpy as np
df2=df2.replace(1,0)
df2

№ Summer  01 !  02 !  03 !  \
Afghanistan (AFG)                                   13     0     0     2   
Algeria (ALG)                                       12     5     2     8   
Argentina (ARG)                                     23    18    24    28   
Armenia (ARM)                                        5     0     2     9   
Australasia (ANZ) [ANZ]                              2     3     4     5   
Australia (AUS) [AUS] [Z]                           25   139   152   177   
Austria (AUT)                                       26    18    33    35   
Azerbaijan (AZE)                                     5     6     5    15   
Bahamas (BAH)                                       15     5     2     5   
Bahrain (BRN)                                        8     0     0     0   
Barbados (BAR) [BAR]                                11     0     0     0   
Belarus (BLR)                                        5    12    24    39   
Belgium (BEL)                                       25    37    52    53   
Bermuda (BER)                                       17     0     0     0   
Bohemia (BOH) [BOH] [Z]                              3     0     0     3   
Botswana (BOT)                                       9     0     0     0   
Brazil (BRA)                                        21    23    30    55   
British West Indies (BWI) [BWI]                      0     0     0     2   
Bulgaria (BUL) [H]                                  19    51    85    78   
Burundi (BDI)                                        5     0     0     0   
Cameroon (CMR)                                      13     3     0     0   
Canada (CAN)                                        25    59    99   121   
Chile (CHI) [I]                                     22     2     7     4   
China (CHN) [CHN]                                    9   201   146   126   
Colombia (COL)                                      18     2     6    11   
Costa Rica (CRC)                                    14     0     0     2   
Ivory Coast (CIV) [CIV]                             12     0     0     0   
Croatia (CRO)                                        6     6     7    10   
Cuba (CUB) [Z]                                      19    72    67    70   
Cyprus (CYP)                                         9     0     0     0   
...                                                ...   ...   ...   ...   
Sri Lanka (SRI) [SRI]                               16     0     2     0   
Sudan (SUD)                                         11     0     0     0   
Suriname (SUR) [E]                                  11     0     0     0   
Sweden (SWE) [Z]                                    26   143   164   176   
Switzerland (SUI)                                   27    47    73    65   
Syria (SYR)                                         12     0     0     0   
Chinese Taipei (TPE) [TPE] [TPE2]                   13     2     7    12   
Tajikistan (TJK)                                     5     0     0     2   
Tanzania (TAN) [TAN]                                12     0     2     0   
Thailand (THA)                                      15     7     6    11   
Togo (TOG)                                           9     0     0     0   
Tonga (TGA)                                          8     0     0     0   
Trinidad and Tobago (TRI) [TRI]                     16     2     5    11   
Tunisia (TUN)                                       13     3     3     4   
Turkey (TUR)                                        21    39    25    24   
Uganda (UGA)                                        14     2     3     2   
Ukraine (UKR)                                        5    33    27    55   
United Arab Emirates (UAE)                           8     0     0     0   
United States (USA) [P] [Q] [R] [Z]                 26   976   757   666   
Uruguay (URU)                                       20     2     2     6   
Uzbekistan (UZB)                                     5     5     5    10   
Venezuela (VEN)   

In [181]:
df3=df2[:10]
df3

№ Summer  01 !  02 !  03 !  Total  № Winter  \
Afghanistan (AFG)                13     0     0     2      2         0   
Algeria (ALG)                    12     5     2     8     15         3   
Argentina (ARG)                  23    18    24    28     70        18   
Armenia (ARM)                     5     0     2     9     12         6   
Australasia (ANZ) [ANZ]           2     3     4     5     12         0   
Australia (AUS) [AUS] [Z]        25   139   152   177    468        18   
Austria (AUT)                    26    18    33    35     86        22   
Azerbaijan (AZE)                  5     6     5    15     26         5   
Bahamas (BAH)                    15     5     2     5     12         0   
Bahrain (BRN)                     8     0     0     0      0         0   

                           01 !.1  02 !.1  03 !.1  Total.1  № Games  01 !.2  \
Afghanistan (AFG)               0       0       0        0       13       0   
Algeria (ALG)                   0       0       0        0       15       5   
Argentina (ARG)                 0       0       0        0       41      18   
Armenia (ARM)                   0       0       0        0       11       0   
Australasia (ANZ) [ANZ]         0       0       0        0        2       3   
Australia (AUS) [AUS] [Z]       5       3       4       12       43     144   
Austria (AUT)                  59      78      81      218       48      77   
Azerbaijan (AZE)                0       0       0        0       10       6   
Bahamas (BAH)                   0       0       0        0       15       5   
Bahrain (BRN)                   0       0       0        0        8       0   

                           02 !.2  03 !.2  Combined total  
Afghanistan (AFG)               0       2               2  
Algeria (ALG)                   2       8              15  
Argentina (ARG)                24      28              70  
Armenia (ARM)                   2       9              12  
Australasia (ANZ) [ANZ]         4       5              12  
Australia (AUS) [AUS] [Z]     155     181             480  
Austria (AUT)                 111     116             304  
Azerbaijan (AZE)                5      15              26  
Bahamas (BAH)                   2       5              12  
Bahrain (BRN)                   0       0               0

In [184]:
#df2=df2.drop(df.iloc[:10],axis=0,inplace=True)
df2

№ Summer  01 !  02 !  03 !  \
Afghanistan (AFG)                                   13     0     0     2   
Algeria (ALG)                                       12     5     2     8   
Argentina (ARG)                                     23    18    24    28   
Armenia (ARM)                                        5     0     2     9   
Australasia (ANZ) [ANZ]                              2     3     4     5   
Australia (AUS) [AUS] [Z]                           25   139   152   177   
Austria (AUT)                                       26    18    33    35   
Azerbaijan (AZE)                                     5     6     5    15   
Bahamas (BAH)                                       15     5     2     5   
Bahrain (BRN)                                        8     0     0     0   
Barbados (BAR) [BAR]                                11     0     0     0   
Belarus (BLR)                                        5    12    24    39   
Belgium (BEL)                                       25    37    52    53   
Bermuda (BER)                                       17     0     0     0   
Bohemia (BOH) [BOH] [Z]                              3     0     0     3   
Botswana (BOT)                                       9     0     0     0   
Brazil (BRA)                                        21    23    30    55   
British West Indies (BWI) [BWI]                      0     0     0     2   
Bulgaria (BUL) [H]                                  19    51    85    78   
Burundi (BDI)                                        5     0     0     0   
Cameroon (CMR)                                      13     3     0     0   
Canada (CAN)                                        25    59    99   121   
Chile (CHI) [I]                                     22     2     7     4   
China (CHN) [CHN]                                    9   201   146   126   
Colombia (COL)                                      18     2     6    11   
Costa Rica (CRC)                                    14     0     0     2   
Ivory Coast (CIV) [CIV]                             12     0     0     0   
Croatia (CRO)                                        6     6     7    10   
Cuba (CUB) [Z]                                      19    72    67    70   
Cyprus (CYP)                                         9     0     0     0   
...                                                ...   ...   ...   ...   
Sri Lanka (SRI) [SRI]                               16     0     2     0   
Sudan (SUD)                                         11     0     0     0   
Suriname (SUR) [E]                                  11     0     0     0   
Sweden (SWE) [Z]                                    26   143   164   176   
Switzerland (SUI)                                   27    47    73    65   
Syria (SYR)                                         12     0     0     0   
Chinese Taipei (TPE) [TPE] [TPE2]                   13     2     7    12   
Tajikistan (TJK)                                     5     0     0     2   
Tanzania (TAN) [TAN]                                12     0     2     0   
Thailand (THA)                                      15     7     6    11   
Togo (TOG)                                           9     0     0     0   
Tonga (TGA)                                          8     0     0     0   
Trinidad and Tobago (TRI) [TRI]                     16     2     5    11   
Tunisia (TUN)                                       13     3     3     4   
Turkey (TUR)                                        21    39    25    24   
Uganda (UGA)                                        14     2     3     2   
Ukraine (UKR)                                        5    33    27    55   
United Arab Emirates (UAE)                           8     0     0     0   
United States (USA) [P] [Q] [R] [Z]                 26   976   757   666   
Uruguay (URU)                                       20     2     2     6   
Uzbekistan (UZB)                                     5     5     5    10   
Venezuela (VEN)   

In [1]:
l=[]
sum(l)

0

# Probability and Statistics:
* Probability is a study of random events
* Probably - unlikely 

* statistics  - Group, data samples(uniform) / subset of population
    * Descriptive (Describe data set / visualizations / summary) :
        * central tendancy - mean/ median 
        * measures of dispersion - range , stadardndeviation, variance etc
    * Inferential statistics (Conclusion / Prediction / To Generalize the data):
        * 
### Statistical Analysis
* Desciptive:

    * Data Collection : Collecting Data from Population
    * Desciptive statistics : summarizing data, visualization data
*
    * Exploratory data analysis - EDA : patterns, differences , identity limitations
    * Estimation : estimate characteristics
    * Hypothesis testing : 
* Raw Data : directly take value
* Recode : calculated from raw data like (Total in olympics)


sample size = frequency/total number pof samples





In [4]:
m=[23,34,54]
mean = sum(m)/len(m)
mean

37.0

In [8]:
import  numpy as np
n=np.array(m)
n.mean()


37.0

In [11]:
sumSigma =0
for i in m:
    sumSigma += (i - mean)**2
variance = sumSigma / len(m)
stdDeviation = variance ** 0.5
stdDeviation



12.832251036613439

In [41]:
from collections import Counter 
marks = [100,1,1,2,1,2,100,23]
di=Counter(marks)
di=dict(di)
di

{100: 2, 1: 3, 2: 2, 23: 1}

In [43]:
for k,v in di.items():
    if v == max(di.values()):
        print(k)

1


In [38]:
max(di.values())

2

In [ ]:
values to frequency is probability
probability to values PMF Probability 

In [26]:
d=sorted(marks)
d

[1, 1, 2, 2, 23, 100, 100]

In [30]:
median = d[len(d)//2]
median
d

[1, 1, 2, 2, 23, 100, 100]

In [12]:
l=[2,3,4]
l1=[3,7,4,5]
l+l1


[2, 3, 4, 3, 7, 4, 5]

In [10]:
l.extend(l1)
l

[2, 3, 4, 3, 7, 4, 5, 3, 7, 4, 5, 3, 7, 4, 5]

In [13]:
dir(())

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

In [34]:

l2=[9,3,1,7,2,8,4,7]
l2

[9, 3, 1, 7, 2, 8, 4, 7]

In [30]:

l2=sorted(l2[:len(l2)//2])+sorted(l2[len(l2)//2:],reverse=True)
l2

[1, 3, 7, 9, 8, 7, 4, 2]

In [35]:

l2=sorted(l2[:4])+sorted(l2[4:],reverse=True)
l2

[1, 3, 7, 9, 8, 7, 4, 2]

In [48]:
def fun():
                                                                       print("dnmfb")
                                                                       print("dfjkdshf")
fun()

dnmfb
dfjkdshf


In [50]:
# Positional Arguments

def std(id,name,mark):
    print(id,name,mark)
std(12,"mercy",234)

12 mercy 234


In [146]:
def teacher(t):
    print(t)

def std(id,name,mark): # marks = 60  defalut arguments
    print(id,name,mark)
    return id
#std(12,"mercy",234)
t=std(12,"m3e",23)
teacher(t)

12 m3e 23
12


In [59]:
def teacher(t):
    print(t)

def std(id=3,name,mark): # syntax error== After completing non_defalut arguments then give default arguments
    print(id,name,mark)
    return id
#std(12,"mercy",234)
t=std(12,"m3e",23)
teacher(t)

SyntaxError: non-default argument follows default argument (<ipython-input-59-30964b08deb0>, line 4)

In [72]:
# Use local variables as global 
id=6
def student(name):
    global id
    id =4
    print(id,name)
    
print(id)
student("fd")
print(id)

6
4 fd
4


In [86]:
# 
def std():
    id=2
    name = "dnfm"

    marks = 34
    
    def teacher():
        nonlocal marks
        marks=24
    teacher()
    print(marks)
    
std()
#print(marks)

24


In [92]:
# variable length arguments

def add(a,b):
    c=a + b
    return c
add(2,4)


6

In [95]:
def add(a,*b):
    c=a + sum(b)
    return c
add(2,4,4,5,6)

21

In [99]:
def add(a,*b):  # always gives * to last arguments
    sum=0
    for i in b:
        sum+=i
    return sum+a
add(2,4,4,5,6)

21

In [104]:
# keyword arguments **kwargs

def add1(**n):
    sum=0
    for i in n.values():
        sum+=int(i)
        
    return sum

add1(a=1,b=3,c=6)

10

In [105]:
def add1(**n):
    for k,v in n.items():
        print(k,v)

add1(name="Mercy",num=447)

name Mercy
num 447


In [110]:
import keyword
keyword.kwlist   

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [ ]:
# Local server
# Staging server
# Production server

In [142]:
try:
    c=0
    a = input("enter a value")
#     a ="1"
    b = 5
    c = a+b   # here a is str and b is int so type error
    print(c)
except TypeError: 
    a = int(input("enter value"))
    b=45
    c=a+b
    print(c)
else:
    print("all okay")           
    
finally:
    a = 5
    b = 6
    c=a+b
    print(c)    # if try and except not work then directly go to finally block

enter a value4
enter value5
50
11


In [143]:
try:
    c=0
    a = input("enter a value")
#     a ="1"
    b = "5"
    c = a+b   # here a is str and b is int so type error
    print(c)
except TypeError: 
    a = int(input("enter value"))    
    b=45
    c=a+b
    print(c)
else:                             # if try work except not work then execute else block 
    print("all okay")
    
finally:
    a = 5
    b = 6
    c=a+b
    print(c)

enter a value3
35
all okay
11


In [144]:
sum=0
while 1:
    try:
        n = int(input())
        sum+=n
    except:
        break
    
    
print(sum)

3
4
5
6

18


In [149]:
n="4"
n+5

TypeError: can only concatenate str (not "int") to str

In [150]:
10/0

ZeroDivisionError: division by zero

In [ ]:
^[9876]{1}[0-9]{9}$   for Phone validation





In [153]:
import collections
help(collections)

Help on package collections:

NAME
    collections

DESCRIPTION
    This module implements specialized container datatypes providing
    alternatives to Python's general purpose built-in containers, dict,
    list, set, and tuple.
    
    * namedtuple   factory function for creating tuple subclasses with named fields
    * deque        list-like container with fast appends and pops on either end
    * ChainMap     dict-like class for creating a single view of multiple mappings
    * Counter      dict subclass for counting hashable objects
    * OrderedDict  dict subclass that remembers the order entries were added
    * defaultdict  dict subclass that calls a factory function to supply missing values
    * UserDict     wrapper around dictionary objects for easier dict subclassing
    * UserList     wrapper around list objects for easier list subclassing
    * UserString   wrapper around string objects for easier string subclassing

PACKAGE CONTENTS
    abc

SUBMODULES
    _collections

In [18]:
import datetime 
d=datetime.datetime.now()
d

datetime.datetime(2019, 11, 21, 9, 54, 40, 404281)

In [11]:
d.day

21

In [16]:
d.month

11

In [12]:
d.year

2019

In [13]:
d.hour

9

In [14]:
d.second

14

In [15]:
d.microsecond

964624

In [23]:
import calendar as c
dir(calendar)

['Calendar',
 'EPOCH',
 'FRIDAY',
 'February',
 'HTMLCalendar',
 'IllegalMonthError',
 'IllegalWeekdayError',
 'January',
 'LocaleHTMLCalendar',
 'LocaleTextCalendar',
 'MONDAY',
 'SATURDAY',
 'SUNDAY',
 'THURSDAY',
 'TUESDAY',
 'TextCalendar',
 'WEDNESDAY',
 '_EPOCH_ORD',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_colwidth',
 '_locale',
 '_localized_day',
 '_localized_month',
 '_spacing',
 'c',
 'calendar',
 'datetime',
 'day_abbr',
 'day_name',
 'different_locale',
 'error',
 'firstweekday',
 'format',
 'formatstring',
 'isleap',
 'leapdays',
 'main',
 'mdays',
 'month',
 'month_abbr',
 'month_name',
 'monthcalendar',
 'monthlen',
 'monthrange',
 'nextmonth',
 'prcal',
 'prevmonth',
 'prmonth',
 'prweek',
 'repeat',
 'setfirstweekday',
 'sys',
 'timegm',
 'week',
 'weekday',
 'weekheader']

In [25]:
print(c.month(2019,11))

   November 2019
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30



In [26]:
print(c.month(2020,11))

   November 2020
Mo Tu We Th Fr Sa Su
                   1
 2  3  4  5  6  7  8
 9 10 11 12 13 14 15
16 17 18 19 20 21 22
23 24 25 26 27 28 29
30



In [27]:
c.isleap(2020)

True

In [28]:
c.monthrange(2019,11) # 4weeks 30days in 11-2019

(4, 30)

In [29]:
c.weekday(2019,11,22) # 4 is for friday 0-6 mon to sun

4

In [33]:
print(c.leapdays(2000,2020))

5


In [47]:
import time as t
dir(time)

['_STRUCT_TM_ITEMS',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'altzone',
 'asctime',
 'clock',
 'ctime',
 'daylight',
 'get_clock_info',
 'gmtime',
 'localtime',
 'mktime',
 'monotonic',
 'monotonic_ns',
 'perf_counter',
 'perf_counter_ns',
 'process_time',
 'process_time_ns',
 'sleep',
 'strftime',
 'strptime',
 'struct_time',
 'thread_time',
 'thread_time_ns',
 'time',
 'time_ns',
 'timezone',
 'tzname']

In [50]:
t.localtime(time.time())

time.struct_time(tm_year=2019, tm_mon=11, tm_mday=21, tm_hour=10, tm_min=29, tm_sec=48, tm_wday=3, tm_yday=325, tm_isdst=0)

In [56]:
from datetime import date
today=date.today()
today

datetime.date(2019, 11, 21)

In [59]:
d2=today.strftime("%d %B %y")
d2

'21 November 19'

In [60]:
d3=today.strftime("%d %m %y")
d3

'21 11 19'

In [62]:
calendar.prcal(2020)

                                  2020

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                      1  2                         1
 6  7  8  9 10 11 12       3  4  5  6  7  8  9       2  3  4  5  6  7  8
13 14 15 16 17 18 19      10 11 12 13 14 15 16       9 10 11 12 13 14 15
20 21 22 23 24 25 26      17 18 19 20 21 22 23      16 17 18 19 20 21 22
27 28 29 30 31            24 25 26 27 28 29         23 24 25 26 27 28 29
                                                    30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                   1  2  3       1  2  3  4  5  6  7
 6  7  8  9 10 11 12       4  5  6  7  8  9 10       8  9 10 11 12 13 14
13 14 15 16 17 18 19      11 12 13 14 15 16 17      15 16 17 18 19 20 21
20 21 22 23 24 25 26      18 19 20 21 22 

In [64]:
type(-4)

int

In [2]:
from tkinter  import *
tk = Tk()
canvas = Canvas(tk,width=400,height=400)
canvas.pack()
canvas.create_arc(10,10,200,100,extent=180)
tk.mainloop()

In [3]:
import turtle
t=turtle.Pen()
t.color(1,0,0)
t.begin_fill()
t.forward(100)
t.left(90)

In [5]:
tk = Tk()
btn =Button(tk, text="click me")
btn.pack()

# Numpy 

In [42]:
import numpy as np
d=np.random.rand(3,3)
d

array([[0.99199513, 0.70116868, 0.9279274 ],
       [0.38329563, 0.32965956, 0.0287424 ],
       [0.07210772, 0.54139269, 0.3194757 ]])

In [43]:
import numpy as np
dd=np.random.randn(3,3)
d=d*10
dd

array([[ 0.56504854, -2.55292243, -0.32417476],
       [-0.64846276, -0.44657799,  0.44493228],
       [ 0.8849277 ,  1.1187518 ,  0.0744    ]])

In [45]:
import numpy as np
dd=np.random.randint(100)

dd

62

In [50]:
import numpy as np
dd=np.random.random(100)
dd

array([0.35710644, 0.6792544 , 0.86414418, 0.64580959, 0.37249421,
       0.97476108, 0.45265745, 0.51589719, 0.6508523 , 0.18987677,
       0.7205098 , 0.8061793 , 0.56133122, 0.68934661, 0.39167294,
       0.24020215, 0.92906762, 0.82634281, 0.18734524, 0.24858391,
       0.40077445, 0.49722896, 0.35909519, 0.97379135, 0.56600354,
       0.83795675, 0.21720707, 0.08812999, 0.67387282, 0.29601632,
       0.82385794, 0.89402569, 0.70215095, 0.69902627, 0.71170064,
       0.14582416, 0.76033434, 0.799305  , 0.95770369, 0.78583666,
       0.51039128, 0.28379786, 0.81428184, 0.37262838, 0.96835587,
       0.57552359, 0.85005404, 0.07227009, 0.40399377, 0.3387346 ,
       0.06923606, 0.6818639 , 0.0619089 , 0.38009138, 0.2845643 ,
       0.12387697, 0.44865937, 0.74071887, 0.09250193, 0.19846318,
       0.65585819, 0.26704219, 0.78445812, 0.35151055, 0.19699878,
       0.38604249, 0.2866345 , 0.73466817, 0.17775917, 0.02508639,
       0.02678714, 0.14117749, 0.30285289, 0.267543  , 0.31709

In [15]:
d+d

array([[15.6034183 , 18.2851963 , 13.89137981],
       [17.48799414,  3.11914698, 14.67928016],
       [12.75508591, 18.34047043,  8.51978124]])

In [19]:
f=np.array([[1,2,3],[4,5,6]])
f

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
f**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [21]:
1/f

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [22]:
f-f

array([[0, 0, 0],
       [0, 0, 0]])

In [51]:
f>2

array([[False, False,  True],
       [ True,  True,  True]])

In [60]:
arr=np.arange(10.5)
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [55]:
arr[5:7]

array([5, 6])

In [56]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [64]:
arr[5:8]=12
arr

array([ 0.,  1.,  2.,  3.,  4., 12., 12., 12.,  8.,  9., 10.])

In [65]:
arr_s=arr[5:8]
arr_s


array([12., 12., 12.])

In [66]:
arr_s[1]=123
arr_s

array([ 12., 123.,  12.])

In [67]:
arr

array([  0.,   1.,   2.,   3.,   4.,  12., 123.,  12.,   8.,   9.,  10.])

In [76]:
array=np.array([[1,2,3],[4,5,6],[8,9,0]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 0]])

In [77]:
array.flatten("C") # Row wise concat and single dimention

array([1, 2, 3, 4, 5, 6, 8, 9, 0])

In [78]:
array.flatten("F")# column wise concat and single dimention

array([1, 4, 8, 2, 5, 9, 3, 6, 0])

In [83]:
g=np.arange(16).reshape(4,4)
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
g[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [94]:
g[1:4:2,1:4:2]


array([[ 5,  7],
       [13, 15]])

In [96]:
g[1:4:2,0:4:2]

array([[ 4,  6],
       [12, 14]])

In [105]:
arr1=np.arange(1,10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
arr1[1:2,1:]=0
arr1

array([[1, 2, 3],
       [4, 0, 0],
       [7, 8, 9]])

In [112]:
arr1[::-1,::-1]

array([[9, 8, 7],
       [0, 0, 4],
       [3, 2, 1]])

In [119]:
arr1[-1,-1]

9

In [122]:
arr1[1,2]


0

# Boolean Indexing

In [152]:
n=np.array(["a","b","a","e","e"])
data=np.random.rand(5,4)
print(n)
data

['a' 'b' 'a' 'e' 'e']


array([[0.38016002, 0.90537006, 0.96560618, 0.60841753],
       [0.47907458, 0.71174569, 0.98311242, 0.02082719],
       [0.61885318, 0.2266683 , 0.97540096, 0.13586258],
       [0.88090552, 0.28341345, 0.05331852, 0.6668619 ],
       [0.57686545, 0.37018013, 0.29823439, 0.38142444]])

In [128]:
n=="e"

array([False, False, False,  True,  True])

In [129]:
data[n=="e"]

array([[0.20977024, 0.49937676, 0.11546401, 0.91310624],
       [0.15089834, 0.08994733, 0.23109637, 0.50761597]])

In [130]:
data[n=="e",2:]

array([[0.11546401, 0.91310624],
       [0.23109637, 0.50761597]])

In [136]:
print(data[n=="a",3])
data[n=="a"]

[0.21939517 0.0084655 ]


array([[0.20212776, 0.50557916, 0.78450523, 0.21939517],
       [0.00430589, 0.97657828, 0.9490333 , 0.0084655 ]])

In [153]:
n=np.array([22,33,44,33,22])
data=np.random.randn(5,5)
print(n)
data

[22 33 44 33 22]


array([[ 0.18358878,  0.7791892 , -0.75577908,  0.7857629 ,  0.62867101],
       [ 0.29773914,  0.42713466,  1.22437917,  0.12069771, -0.11224172],
       [-0.67841114, -1.48209535,  0.06064821,  1.49305598,  1.2039119 ],
       [-0.41627509,  2.23694623,  1.18126343,  0.34458547, -0.51375516],
       [-0.28905738, -0.19432919,  1.86670128, -0.41364491, -0.26730832]])

In [140]:
data[n!=22]

array([[0.18433841, 0.72100162, 0.85494771, 0.45785697, 0.02244101],
       [0.75522939, 0.24961559, 0.89003618, 0.15594685, 0.39846611],
       [0.97996691, 0.16009477, 0.71878049, 0.06534875, 0.50586438]])

In [144]:
c=n==22
c

array([ True, False, False, False,  True])

In [147]:
data

array([[0.52409821, 0.74357673, 0.65710714, 0.58828799, 0.89706721],
       [0.18433841, 0.72100162, 0.85494771, 0.45785697, 0.02244101],
       [0.75522939, 0.24961559, 0.89003618, 0.15594685, 0.39846611],
       [0.97996691, 0.16009477, 0.71878049, 0.06534875, 0.50586438],
       [0.47764737, 0.32528627, 0.60454163, 0.89043881, 0.74528263]])

In [146]:
data[c]

array([[0.52409821, 0.74357673, 0.65710714, 0.58828799, 0.89706721],
       [0.47764737, 0.32528627, 0.60454163, 0.89043881, 0.74528263]])

In [145]:
data[~c]

array([[0.18433841, 0.72100162, 0.85494771, 0.45785697, 0.02244101],
       [0.75522939, 0.24961559, 0.89003618, 0.15594685, 0.39846611],
       [0.97996691, 0.16009477, 0.71878049, 0.06534875, 0.50586438]])

In [156]:
data[data<0]=0
data

array([[0.18358878, 0.7791892 , 0.        , 0.7857629 , 0.62867101],
       [0.29773914, 0.42713466, 1.22437917, 0.12069771, 0.        ],
       [0.        , 0.        , 0.06064821, 1.49305598, 1.2039119 ],
       [0.        , 2.23694623, 1.18126343, 0.34458547, 0.        ],
       [0.        , 0.        , 1.86670128, 0.        , 0.        ]])

In [159]:
data[(n==22 )| (n==33)]

array([[0.18358878, 0.7791892 , 0.        , 0.7857629 , 0.62867101],
       [0.29773914, 0.42713466, 1.22437917, 0.12069771, 0.        ],
       [0.        , 2.23694623, 1.18126343, 0.34458547, 0.        ],
       [0.        , 0.        , 1.86670128, 0.        , 0.        ]])

In [161]:
data[n!=22]=7
data

array([[0.18358878, 0.7791892 , 0.        , 0.7857629 , 0.62867101],
       [7.        , 7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 1.86670128, 0.        , 0.        ]])

In [167]:
ar=np.empty((8,4))
ar

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [175]:
for i in range(8):
    ar[i]=i
ar

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [187]:
ar[[4,3,0,6]][:,1:3] #4,3,0,6 rows


array([[4., 4.],
       [3., 3.],
       [0., 0.],
       [6., 6.]])

In [190]:
ar[[-3,-5,-4,-1]][:,[0,2,3]] # -3,-5,-4,-1 rows then 0,2,3 columns

array([[5., 5., 5.],
       [3., 3., 3.],
       [4., 4., 4.],
       [7., 7., 7.]])

In [191]:
ar[[1,3,2,3],[0,1,3,2]] # 1row ocloumn n 3row 1column 

array([1., 3., 2., 3.])

In [195]:
print(ar)
print(ar.T)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7.]]


In [211]:
a=np.arange(16).reshape((2,2,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [219]:
print(a.transpose((1,0,2)))
print(a.transpose((2,0,1)))

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]
[[[ 0  4]
  [ 8 12]]

 [[ 1  5]
  [ 9 13]]

 [[ 2  6]
  [10 14]]

 [[ 3  7]
  [11 15]]]


# Pandas

In [2]:
import pandas as pd
obj=pd.Series([2,-2,23,5])
obj

0     2
1    -2
2    23
3     5
dtype: int64

In [3]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [4]:
obj.values

array([ 2, -2, 23,  5], dtype=int64)

In [9]:
import pandas as pd
obj2=pd.Series([2,-2,23,5],index=[1.1,2.2,3.3,4.4])
obj2

1.1     2
2.2    -2
3.3    23
4.4     5
dtype: int64

In [11]:
obj3=pd.Series([2,-2,23,5],index=["a","b","c","d"])
obj3

a     2
b    -2
c    23
d     5
dtype: int64

In [10]:
obj2[4.4]=0
obj2

1.1     2
2.2    -2
3.3    23
4.4     0
dtype: int64

In [12]:
obj3[obj3>2]

c    23
d     5
dtype: int64

In [13]:
obj2*2

1.1     4
2.2    -4
3.3    46
4.4     0
dtype: int64

In [15]:
obj2[4.4]=1
obj2

1.1     2
2.2    -2
3.3    23
4.4     1
dtype: int64

In [17]:
import numpy as np
np.exp(obj2)

1.1    7.389056e+00
2.2    1.353353e-01
3.3    9.744803e+09
4.4    2.718282e+00
dtype: float64

In [24]:
obj2[3.8]=5
obj2

1.1     2
2.2    -2
3.3    23
4.4     4
3.2     4
3.8     5
dtype: int64

In [25]:
2 in obj2

False

In [27]:
3.2 in obj2

True

In [28]:
dic={"chitti":95,"thotti":35,"potti":99}
ob=pd.Series(dic)
ob

chitti    95
thotti    35
potti     99
dtype: int64

In [30]:
st=["Merc","chitti","potti"]
obj=pd.Series(ob,index=st)
obj

Merc       NaN
chitti    95.0
potti     99.0
dtype: float64

In [34]:
pd.isnull(obj)
obj.isnull()

Merc       True
chitti    False
potti     False
dtype: bool

In [35]:
pd.notnull(obj)
obj.notnull()

Merc      False
chitti     True
potti      True
dtype: bool

In [37]:
obj+ob # if both are values present then only add else NaN

Merc        NaN
chitti    190.0
potti     198.0
thotti      NaN
dtype: float64