In [14]:
import pandas as pd
dt = pd.read_csv("supermarket_sales.csv")
dt.sample(10)

Invoice ID Branch       City Customer type  Gender  \
455  767-54-1907      B   Mandalay        Member  Female   
28   145-94-9061      B   Mandalay        Normal  Female   
917  749-81-8133      A     Yangon        Normal  Female   
989  430-53-4718      B   Mandalay        Member    Male   
435  751-69-0068      C  Naypyitaw        Normal    Male   
386  689-16-9784      C  Naypyitaw        Normal    Male   
108  588-01-7461      C  Naypyitaw        Normal  Female   
280  136-08-6195      A     Yangon        Normal  Female   
978  156-20-0370      B   Mandalay        Normal  Female   
633  420-04-7590      B   Mandalay        Normal    Male   

               Product line  Unit price  Quantity   Tax 5%     Total  \
455     Fashion accessories       29.56         5   7.3900  155.1900   
28       Food and beverages       88.36         5  22.0900  463.8900   
917     Fashion accessories       94.67         4  18.9340  397.6140   
989       Health and beauty       75.37         8  30.1480  633.1080   
435       Sports and travel       99.24         9  44.6580  937.8180   
386      Food and beverages       46.77         6  14.0310  294.6510   
108      Food and beverages       33.98         9  15.2910  321.1110   
280      Home and lifestyle       69.96         8  27.9840  587.6640   
978  Electronic accessories       25.45         1   1.2725   26.7225   
633      Home and lifestyle       99.70         3  14.9550  314.0550   

          Date   Time      Payment    cogs  gross margin percentage  \
455  2/13/2019  16:59         Cash  147.80                 4.761905   
28   1/25/2019  19:48         Cash  441.80                 4.761905   
917  3/11/2019  12:04         Cash  378.68                 4.761905   
989  1/28/2019  15:46  Credit card  602.96                 4.761905   
435  3/19/2019  19:09      Ewallet  893.16                 4.761905   
386  3/11/2019  13:37         Cash  280.62                 4.761905   
108  3/24/2019  10:43         Cash  305.82                 4.761905   
280  2/15/2019  17:01  Credit card  559.68                 4.761905   
978  3/10/2019  18:10  Credit card   25.45                 4.761905   
633  3/18/2019  11:29      Ewallet  299.10                 4.761905   

     gross income  Rating  
455        7.3900     6.9  
28        22.0900     9.6  
917       18.9340     6.8  
989       30.1480     8.4  
435       44.6580     9.0  
386       14.0310     6.0  
108       15.2910     4.2  
280       27.9840     6.4  
978        1.2725     5.1  
633       14.9550     4.7

In [16]:
dt[["City"]].head(2)

City
0     Yangon
1  Naypyitaw

In [22]:
x= dt[["Customer type","gross income","Branch"]]
x.head()

Customer type  gross income Branch
0        Member       26.1415      A
1        Normal        3.8200      C
2        Normal       16.2155      A
3        Member       23.2880      A
4        Normal       30.2085      A

In [21]:
x["Customer type"] = pd.get_dummies(x["Customer type"],drop_first = True)
yy = x[["Customer type"]]
yy.head()

C:\Users\APSSDC\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


Customer type
0              0
1              1
2              1
3              0
4              1

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
print(y)

In [106]:
bird = pd.read_csv("bird.csv")
bird.sample(20)


id    huml   humw   ulnal  ulnaw   feml  femw    tibl  tibw   tarl  \
331  331   20.19   1.85   26.41   1.53  15.71  1.29   29.66  1.15  21.90   
103  103   68.50   3.77   71.15   3.34  24.86  1.95   51.44  2.10  30.13   
139  139   84.92   7.90   63.16   5.78  46.77  3.84   82.87  4.36  37.17   
403  403   20.95   1.89   24.12   1.66  21.24  1.84   36.71  1.53  25.99   
42    42  147.00   8.44  155.00   5.90  58.41  6.87  108.97  7.63  63.40   
84    84   90.49   4.70   97.02   4.11  29.97  2.53   58.83  2.67  34.32   
180  180   87.01   5.18   94.34   4.45  35.73  2.80   67.12  2.93  43.43   
85    85   89.59   5.11   98.02   4.46  29.96  2.55   58.09  2.79  34.40   
275  275   39.98   3.34   47.50   2.64  28.57  2.53   42.96  2.20  27.66   
287  287   27.72   2.67   32.00   2.21  22.68  2.13   32.50  1.76  19.65   
232  232  145.00  10.37  188.00   7.92  77.09  7.75  125.48  7.90  51.99   
11    11  186.00   9.83  152.00   8.76  56.02  7.02  185.00  8.07  90.80   
215  215   81.39   5.77   94.83   4.80  65.97  5.52   91.63  5.38  73.29   
172  172   64.75   4.27   70.13   3.91  41.82  3.23   86.50  3.81  65.24   
389  389   19.63   1.76   23.58   1.33  18.85  1.54   33.10  1.34  24.09   
274  274   37.86   3.24   46.72   2.63  27.52  2.26   42.49  1.89  26.88   
114  114   65.66   3.79   61.06   3.35  24.95  2.44   63.76  2.72  40.19   
184  184   48.70   5.46   57.39   3.73  42.56  3.07   52.42  2.85  27.23   
205  205   57.48   4.74   69.06   4.08  57.56  4.80   80.16  4.25  60.54   
23    23   63.62   3.42   59.00   2.75  30.16  2.92   74.66  4.38  39.26   

     tarw type  
331  1.05   SO  
103  2.37   SW  
139  3.23    W  
403  1.23   SO  
42   6.70   SW  
84   2.75   SW  
180  2.34    W  
85   2.94   SW  
275  1.67    P  
287  1.64    P  
232  9.64    R  
11   4.59   SW  
215  5.11    R  
172  3.41    W  
389  1.14   SO  
274  1.54    P  
114  1.89   SW  
184  3.03    T  
205  3.78    R  
23   1.97   SW

In [114]:
x = bird.drop(columns=["id","type"],axis=1)
y = bird[["type"]]

In [109]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
print(y)

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]


C:\Users\APSSDC\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [111]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 0)


In [112]:
bird.isnull().sum()

id       0
huml     1
humw     1
ulnal    3
ulnaw    2
feml     2
femw     1
tibl     2
tibw     1
tarl     1
tarw     1
type     0
dtype: int64

In [113]:
import numpy as np
bird = bird.replace(np.NaN,0)

In [115]:
from sklearn.tree import DecisionTreeRegressor
x_bird = DecisionTreeRegressor(max_depth = 2)
x_bird.fit(x,y)

ValueError: could not convert string to float: 'SW'

In [92]:
y_pred = x_bird.predict(x_test)
y_pred

array([2.24186047, 2.24186047, 3.43801653, 3.43801653, 3.43801653,
       3.43801653, 2.34246575, 2.24186047, 3.43801653, 2.24186047,
       2.24186047, 2.34246575, 3.43801653, 2.34246575, 2.24186047,
       2.24186047, 3.43801653, 0.18181818, 2.24186047, 2.24186047,
       3.43801653, 3.43801653, 2.24186047, 3.43801653, 2.24186047,
       2.24186047, 2.24186047, 2.34246575, 3.43801653, 2.24186047,
       2.24186047, 2.24186047, 2.24186047, 2.24186047, 3.43801653,
       2.24186047, 3.43801653, 3.43801653, 3.43801653, 3.43801653,
       2.34246575, 2.24186047, 3.43801653, 2.24186047, 3.43801653,
       3.43801653, 2.34246575, 2.24186047, 2.24186047, 3.43801653,
       3.43801653, 2.24186047, 3.43801653, 2.24186047, 2.24186047,
       2.24186047, 3.43801653, 3.43801653, 2.24186047, 3.43801653,
       2.24186047, 2.24186047, 2.34246575, 2.34246575, 2.34246575,
       2.24186047, 2.24186047, 2.34246575, 2.24186047, 2.24186047,
       2.24186047, 2.24186047, 3.43801653, 2.34246575, 3.43801

In [103]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train,y_train)
y_pred = gnb.predict(x_test)
y_pred

array([5, 0, 1, 5, 5, 5, 3, 2, 0, 2, 0, 1, 0, 1, 2, 0, 1, 2, 2, 2, 3, 3,
       2, 5, 2, 2, 2, 1, 1, 0, 2, 2, 0, 0, 0, 2, 3, 5, 1, 0, 3, 2, 1, 2,
       5, 5, 1, 0, 2, 5, 5, 0, 1, 2, 2, 0, 5, 1, 2, 5, 2, 2, 3, 1, 1, 2,
       2, 1, 2, 2, 2, 2, 3, 3, 3, 1, 2, 5, 1, 2, 2, 1, 5, 2, 5, 5, 2, 1,
       5, 2, 1, 2, 2, 1, 0, 2, 3, 2, 1, 0, 0, 2, 1, 5, 0, 5, 0, 2, 5, 1,
       2, 0, 1, 2, 5, 0, 5, 3, 1, 1, 5, 0, 2, 0, 2, 2])

In [104]:
x_bird.predict([[54.19,3.16,54.28,3.21,23.08,1.98,53.70,2.04,31.29,1.56]])

AttributeError: 'numpy.ndarray' object has no attribute 'predict'

In [105]:
from sklearn.metrics import confusion_matrix
c_m = confusion_matrix(y_test,y_pred)
c_m

array([[ 3,  0,  6,  0,  0,  0],
       [ 2, 10,  0,  0,  0,  1],
       [ 6,  0, 33,  0,  0,  1],
       [ 3,  8,  2, 11,  0, 13],
       [ 5,  1,  0,  0,  0,  0],
       [ 3,  7,  3,  0,  0,  8]], dtype=int64)

In [100]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.5158730158730159