If you aggregate the predictions of a group of predictors(classifiers or regressors),
you will often get better predictions than with the individual predictor.

*A group of predictors is called an "Ensemble",and this technique is called "Ensemble learning"*


* They combine the decisions from multiple models to improve the overall performance
    
    * Voting 
    * Bagging
    * Boosting


### Voting Classifier



* A very simple way to create an even better classifer is to aggregate the predictions of each classifer and predict the class 
  that gets the most votes

##### Hard_Voting
  
* This majority-vote classifer is called a hard-voting classifier

* This voting classifier often achieves a higher accuracy than the best classifier

* Weighted Majority Vote:
         Example: Model 1 -> 92.35578
                  Model 2 -> 89.54545
                  Model 3 -> 92.35578
                  
                  Predicted = 92.35578

##### Soft_voting
* Soft Voting can only be done when all your classifiers can calculate  probabilities for the outcomes. 

* Soft voting arrives at the best result by averaging out the probabilities  calculated by individual algorithms.

* Weighted Averaging Vote:
        Example: Model 1 -> 92.35578
                 Model 2 -> 89.54545
                 Model 3 -> 92.35578
                 
                 Predicted = Sum of Probabilities of classifiers/Total number of classifiers
                 
                           = (92.35578 + 89.54545 + 92.35578)/3
                           
                           = 91.419003
                             



### Bagging Classifier
* Bagging is one of the Ensemble construction techniques which is also known as Bootstrap Aggregation. 

* Used to improve the accuracy of Classification & Regression Trees (CART)

* 

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('zoo.csv')
df.head()

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        bear     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   

   class_type  
0           1  
1           1  
2           4  
3           1  
4           1

In [3]:
df.class_type.unique()

array([1, 4, 2, 7, 6, 5, 3], dtype=int64)

In [4]:
X = df[df.columns[1:-1]]
X.head()

hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  backbone  \
0     1         0     0     1         0        0         1        1         1   
1     1         0     0     1         0        0         0        1         1   
2     0         0     1     0         0        1         1        1         1   
3     1         0     0     1         0        0         1        1         1   
4     1         0     0     1         0        0         1        1         1   

   breathes  venomous  fins  legs  tail  domestic  catsize  
0         1         0     0     4     0         0        1  
1         1         0     0     4     1         0        1  
2         0         0     1     0     1         0        0  
3         1         0     0     4     0         0        1  
4         1         0     0     4     1         0        1

In [5]:
y = df[df.columns[-1:]]
y.head()

class_type
0           1
1           1
2           4
3           1
4           1

In [6]:
#split the dataset into training and testing data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.25,random_state = 42)

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import VotingClassifier

In [8]:
log_clf = LogisticRegression()
rnd_clf = RandomForestClassifier()
gnb_clf = GaussianNB()

In [9]:
voting_clf = VotingClassifier(estimators=[('lr',log_clf),('rf',rnd_clf),('gb',gnb_clf)],voting = 'hard') # soft
voting_clf.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\ProgramData\An

VotingClassifier(estimators=[('lr',
                              LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='warn',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='warn', tol=0.0001,
                                                 verbose=0, warm_start=False)),
                             ('rf',
                              RandomForestClassifier(bootstrap=True,
                                                     class_weight=None,
                                                     criterion='gini',...
                                        

In [10]:
from sklearn.metrics import accuracy_score
for cls in [log_clf,rnd_clf,gnb_clf,voting_clf]:
    cls.fit(X_train,y_train)
    y_pred = cls.predict(X_test)
    print(cls.__class__.__name__,accuracy_score(y_pred,y_test),'\n')


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression 0.8846153846153846 

RandomForestClassifier 0.9615384615384616 

GaussianNB 0.9615384615384616 

VotingClassifier 0.9615384615384616 



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_sam

In [11]:
(0.8846153846153846+0.9615384615384616+0.9615384615384616)/3

0.935897435897436

### Bagging


In [12]:
import pandas as pd
pima= pd.read_csv("diab.csv")
pima

NTS  PGC  DBP  TSFT  INS   BMI    DPF  Age     Class
0      6  148   72    35    0  33.6  0.627   50  Positive
1      1   85   66    29    0  26.6  0.351   31  Negative
2      4  183   64     0    0  23.3  0.672   32  Positive
3      1   89   66    23   94  28.1  0.167   21  Negative
4      0  137   40    35  168  43.1  2.288   33  Positive
..   ...  ...  ...   ...  ...   ...    ...  ...       ...
763   10  101   76    48  180  32.9  0.171   63  Negative
764    2  122   70    27    0  36.8  0.340   27  Negative
765    5  121   72    23  112  26.2  0.245   30  Negative
766    1  126   60     0    0  30.1  0.349   47  Positive
767    1   93   70    31    0  30.4  0.315   23  Negative

[768 rows x 9 columns]

In [13]:
X = pima[pima.columns[:-1]]
X.head()

NTS  PGC  DBP  TSFT  INS   BMI    DPF  Age
0    6  148   72    35    0  33.6  0.627   50
1    1   85   66    29    0  26.6  0.351   31
2    4  183   64     0    0  23.3  0.672   32
3    1   89   66    23   94  28.1  0.167   21
4    0  137   40    35  168  43.1  2.288   33

In [14]:
y = pima[pima.columns[-1:]]
y

Class
0    Positive
1    Negative
2    Positive
3    Negative
4    Positive
..        ...
763  Negative
764  Negative
765  Negative
766  Positive
767  Negative

[768 rows x 1 columns]

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.25,random_state = 0)

In [16]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

In [17]:
bag_clf = DecisionTreeClassifier()

In [18]:
bag_clf.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [19]:
bag_clf.score(X_test,y_test)

0.734375

In [20]:
bag_classifer = BaggingClassifier(DecisionTreeClassifier())

In [21]:
bag_classifer.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:623: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None,
                                                        criterion='gini',
                                                        max_depth=None,
                                                        max_features=None,
                                                        max_leaf_nodes=None,
                                                        min_impurity_decrease=0.0,
                                                        min_impurity_split=None,
                                                        min_samples_leaf=1,
                                                        min_samples_split=2,
                                                        min_weight_fraction_leaf=0.0,
                                                        presort=False,
                                                        random_state=None,
                                                        splitter='best'),
    

In [22]:
bag_classifer.score(X_test,y_test)

0.796875

### Boosting

In [34]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import LabelEncoder

In [33]:
cancer = load_breast_cancer()
#print(cancer.keys())
X = pd.DataFrame(cancer.data,columns = cancer.feature_names)
y = pd.Categorical.from_codes(cancer.target,cancer.target_names)
y

[malignant, malignant, malignant, malignant, malignant, ..., malignant, malignant, malignant, malignant, benign]
Length: 569
Categories (2, object): [malignant, benign]

In [36]:
encoder = LabelEncoder()
encoded_y  = encoder.fit_transform(y) 

In [37]:
encoded_y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [39]:
y = pd.Series(cancer.target)
y

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Length: 569, dtype: int32

In [50]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state =1)

In [43]:
Dcls = DecisionTreeClassifier(max_depth=2)
Dcls.fit(X,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=2,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [44]:
Dcls.score(X_test,y_test)

0.916083916083916

In [59]:
adsboostcls = AdaBoostClassifier(DecisionTreeClassifier(max_depth=2))
adsboostcls.fit(X,y)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=DecisionTreeClassifier(class_weight=None,
                                                         criterion='gini',
                                                         max_depth=2,
                                                         max_features=None,
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         presort=False,
                                                         random_state=None,
                             

In [67]:
from sklearn.metrics import accuracy_score

In [63]:
y_pred = adsboostcls.predict(X_test)
y_pred.shape
y_test.shape
accuracy_score

(143,)

In [47]:
adsboostcls.score(X_test,y_test)

1.0

In [48]:
from sklearn import metrics

In [66]:
metrics.roc_auc_score(y_test,y_pred)

1.0

In [68]:
metrics.roc_curve(y_test,y_pred)

(array([0., 0., 1.]), array([0., 1., 1.]), array([2, 1, 0]))

In [71]:
import matplotlib.pyplot as plt

In [82]:
#plt.scatter(X_test,y_test)
plt.show()


# ROC Curve

In [86]:
import numpy as np
from sklearn import metrics
y = np.array([1, 1, 2, 2])
scores = np.array([0.1, 0.4, 0.35, 0.8])
fpr, tpr, thresholds = metrics.roc_curve(y, scores, pos_label=2)
fpr
tpr
thresholds

array([1.8 , 0.8 , 0.4 , 0.35, 0.1 ])